services:
  devops:
    build: .
    image: devops:latest
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "10000:10000"
    networks:
      - devopsNet

networks:
  devopsNet:
    external: true

# Build and start the application container
#> docker compose up --build -d